export const komponentenBaum = [
  {
    heading: 'Steuerelement',
    show: false,
    children: [
      { heading: 'Prozessor', show: true },
      { heading: 'Motherboard', show: true },
    ],
  },
  {
    heading: 'Grafik',
    show: false,
    children: [
      { heading: 'GPU', show: true },
      { heading: 'Grafikkarte', show: true },
      { heading: 'VR-Brille', show: true },
    ],
  },
  {
    heading: 'Speicher',
    show: false,
    children: [
      { heading: 'RAM', show: true },
      { heading: 'SD-Karte', show: true },
      { heading: 'Micro-SD', show: true },
      { heading: 'USB-Stick', show: true },
      { heading: 'SSD', show: true },
      { heading: 'HDD', show: true },
      { heading: 'CD', show: true },
      { heading: 'DVD', show: true },
      { heading: 'Blu-ray', show: true },
      { heading: 'NAS', show: true },
      { heading: 'SAN', show: true },
    ],
  },
  {
    heading: 'Sensoren',
    show: false,
    children: [
      { heading: 'Thermometer', show: true },
      { heading: 'Bewegungssensor', show: true },
      { heading: 'Luftfeuchtigkeitssensor', show: true },
    ],
  },
  {
    heading: 'Computer',
    show: false,
    children: [
      { heading: 'Laptop', show: true },
      { heading: 'Thin-Client', show: true },
      { heading: 'Thick-Client', show: true },
      { heading: 'Server', show: true },
      { heading: 'Notebook', show: true },
    ],
  },
  {
    heading: 'Handhelds',
    show: false,
    children: [
      { heading: 'Scanner', show: true },
      { heading: 'E-Reader', show: true },
      { heading: 'Tablets', show: true },
      { heading: 'Smartphone', show: true },
      { heading: 'Spiele-Konsole', show: true },
    ],
  },
  {
    heading: 'Wearables',
    show: false,
    children: [
      { heading: 'Smartglasses', show: true },
      { heading: 'Smartwatch', show: true },
      { heading: 'Fitnesstracker', show: true },
    ],
  },
  {
    heading: 'Schnittstellen',
    show: false,
    children: [
      { heading: 'Dockingstation', show: true },
      { heading: 'USB-Hub', show: true },
      { heading: 'Adapter', show: true },
      { heading: 'USB', show: true },
      { heading: 'USB-C', show: true },
      { heading: 'Displayport', show: true },
      { heading: 'HDMI', show: true },
      { heading: 'VGA', show: true },
    ],
  },
  {
    heading: 'Netzwerk',
    show: false,
    children: [
      { heading: 'Repeater', show: true },
      { heading: 'Modem', show: true },
      { heading: 'Accesspoint', show: true },
      { heading: 'Hub', show: true },
      { heading: 'Router', show: true },
      { heading: 'Switch', show: true },
      { heading: 'Wlan-Adapter', show: true },
      { heading: 'NIC', show: true },
      { heading: 'Firewall', show: true },
    ],
  },
  {
    heading: 'Strom',
    show: false,
    children: [
      { heading: 'Netzteil', show: true },
      { heading: 'Akku/ Batterie', show: true },
      { heading: 'USV', show: true },
      { heading: 'PoE Switch', show: true },
    ],
  },
  {
    heading: 'Peripherie',
    show: false,
    children: [
      { heading: 'Robotik', show: true },
      { heading: 'Drohne', show: true },
      { heading: 'Joystick', show: true },
      { heading: 'Scanner', show: true },
      { heading: 'Mikrofon', show: true },
      { heading: 'Webcam', show: true },
      { heading: 'Headset', show: true },
    ],
  },
  {
    heading: 'Eingabegeräte',
    show: false,
    children: [
      { heading: 'Tastatur', show: true },
      { heading: 'Maus', show: true },
      { heading: 'Touchscreen', show: true },
    ],
  },
  {
    heading: 'Ausgabegeräte',
    show: false,
    children: [
      { heading: 'Lautsprecher', show: true },
      { heading: 'Drucker', show: true },
      { heading: 'Monitor', show: true },
      { heading: 'Display', show: true },
    ],
  },
  {
    heading: 'Audio',
    show: false,
    children: [{ heading: 'Soundkarte', show: true }],
  },
  {
    heading: 'Kühlung',
    show: false,
    children: [
      { heading: 'Kühler', show: true },
      { heading: 'Lüfter', show: true },
      { heading: 'Wasserkühlung', show: true },
      { heading: 'Thermoelektrische Kühlung', show: true },
    ],
  },
]
